import { sql } from '@vercel/postgres';
import { logger } from '@/lib/logger';

// ---------------------------------------------------------------------------
// In-app activity feed.
//
// Every cross-actor event in the system (comments, version uploads, status
// changes, take submissions, retakes, assignments, deadlines, …) is logged
// here per recipient so dashboards can show a unified notification center
// with unread badges and a scrollable history.
//
// The same event is typically also delivered as email through notify.ts —
// this table is what powers the "bell" UI and a longer-term audit trail
// regardless of whether email delivery actually went through.
// ---------------------------------------------------------------------------

export type ActivityEventType =
  | 'review_comment'           // viewer left a comment / annotation on a video version
  | 'comment_resolved'         // a comment was marked resolved
  | 'version_uploaded'         // editor uploaded a new version of the video
  | 'status_changed'           // project / assignment status changed
  | 'narrator_take'            // narrator uploaded a take
  | 'narrator_comment'         // narrator left a comment on a section
  | 'retake_requested'         // owner asked for a retake on a section
  | 'editor_assigned'          // owner assigned an editor to a project
  | 'narrator_assigned'        // owner assigned a narrator to a project
  | 'assignment_approved'      // owner approved the narrator's full-narration upload
  | 'script_updated'           // owner edited the script (sections may have been re-synced)
  | 'deadline_reminder'        // synthetic — generated by a scheduled job near deadlines
  | 'message'                  // 1:1 chat message arrived (inner messaging)
  | 'system';                  // catch-all for anything else

export interface ActivityEvent {
  id: string;
  recipient_collaborator_id: string;
  type: ActivityEventType;
  title: string;
  body: string | null;
  /** Project this event relates to (when applicable). */
  project_id: string | null;
  /** Where the bell row should link to, e.g. /narrate/<token>?section=…. */
  link_path: string | null;
  /** Free-form payload (comment id, version id, etc.) for richer rendering. */
  metadata: Record<string, unknown>;
  read_at: string | null;
  created_at: string;
}

let migrated = false;
export async function ensureActivityFeedSchema() {
  if (migrated) return;
  try {
    await sql`
      CREATE TABLE IF NOT EXISTS activity_events (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        recipient_collaborator_id UUID NOT NULL REFERENCES collaborators(id) ON DELETE CASCADE,
        type TEXT NOT NULL,
        title TEXT NOT NULL,
        body TEXT,
        project_id UUID,
        link_path TEXT,
        metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
        read_at TIMESTAMPTZ,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `;
    try { await sql`CREATE INDEX IF NOT EXISTS idx_activity_events_recipient ON activity_events(recipient_collaborator_id, created_at DESC)`; } catch {}
    try { await sql`CREATE INDEX IF NOT EXISTS idx_activity_events_unread ON activity_events(recipient_collaborator_id) WHERE read_at IS NULL`; } catch {}
    migrated = true;
  } catch (err) {
    logger.error('ensureActivityFeedSchema error', { detail: err instanceof Error ? err.message : String(err) });
  }
}

interface LogArgs {
  recipientCollaboratorId: string;
  type: ActivityEventType;
  title: string;
  body?: string;
  projectId?: string;
  linkPath?: string;
  metadata?: Record<string, unknown>;
}

/**
 * Append an event to a collaborator's feed. Best-effort: never throws to
 * the caller, since these are typically dispatched from the .catch path
 * of a primary mutation (creating a comment, uploading a version, etc.)
 * and a logging failure must not bubble up and obscure the real error.
 */
export async function logActivity(args: LogArgs): Promise<void> {
  await ensureActivityFeedSchema();
  try {
    // workspace_id is NOT NULL on activity_events since migration 0013.
    // project_id is the canonical source when present; otherwise fall back
    // to the recipient collaborator's first workspace via workspace_members.
    // If neither resolves (e.g. an event for a collaborator with no
    // workspace membership) the LEFT JOIN COALESCE returns NULL and the
    // INSERT will fail at the constraint — caught silently below since this
    // is a fire-and-forget telemetry path.
    await sql`
      INSERT INTO activity_events (
        recipient_collaborator_id, type, title, body, project_id, link_path, metadata, workspace_id
      )
      SELECT
        ${args.recipientCollaboratorId}::uuid,
        ${args.type},
        ${args.title},
        ${args.body ?? null},
        ${args.projectId ?? null}::uuid,
        ${args.linkPath ?? null},
        ${JSON.stringify(args.metadata ?? {})}::jsonb,
        COALESCE(p.workspace_id, wm.workspace_id)
      FROM (SELECT 1) AS _
      LEFT JOIN projects p ON p.id = ${args.projectId ?? null}::uuid
      LEFT JOIN workspace_members wm ON wm.user_id = ${args.recipientCollaboratorId}::uuid
      LIMIT 1
    `;
  } catch (err) {
    console.warn('logActivity failed:', err);
  }
}

/**
 * Same as logActivity but writes to multiple recipients atomically. Used
 * when an event is relevant to several collaborators (e.g. a video's
 * comment is visible to both editor and narrator).
 */
export async function logActivityMulti(recipientIds: string[], event: Omit<LogArgs, 'recipientCollaboratorId'>): Promise<void> {
  await ensureActivityFeedSchema();
  if (recipientIds.length === 0) return;
  for (const id of recipientIds) {
    await logActivity({ recipientCollaboratorId: id, ...event });
  }
}

export async function listActivity(collaboratorId: string, opts: { limit?: number; offset?: number; unreadOnly?: boolean } = {}): Promise<ActivityEvent[]> {
  await ensureActivityFeedSchema();
  const limit = Math.min(Math.max(opts.limit ?? 50, 1), 200);
  const offset = Math.max(opts.offset ?? 0, 0);
  const { rows } = opts.unreadOnly
    ? await sql`
        SELECT * FROM activity_events
        WHERE recipient_collaborator_id = ${collaboratorId} AND read_at IS NULL
        ORDER BY created_at DESC
        LIMIT ${limit} OFFSET ${offset}
      `
    : await sql`
        SELECT * FROM activity_events
        WHERE recipient_collaborator_id = ${collaboratorId}
        ORDER BY created_at DESC
        LIMIT ${limit} OFFSET ${offset}
      `;
  return rows.map(r => ({
    ...r,
    metadata: (r.metadata as Record<string, unknown>) ?? {},
  })) as ActivityEvent[];
}

export async function countUnreadActivity(collaboratorId: string): Promise<number> {
  await ensureActivityFeedSchema();
  const { rows } = await sql`
    SELECT COUNT(*)::int AS n FROM activity_events
    WHERE recipient_collaborator_id = ${collaboratorId} AND read_at IS NULL
  `;
  return (rows[0]?.n as number) ?? 0;
}

export async function markActivityRead(collaboratorId: string, opts: { id?: string; all?: boolean }): Promise<void> {
  await ensureActivityFeedSchema();
  if (opts.all) {
    await sql`
      UPDATE activity_events SET read_at = NOW()
      WHERE recipient_collaborator_id = ${collaboratorId} AND read_at IS NULL
    `;
    return;
  }
  if (opts.id) {
    await sql`
      UPDATE activity_events SET read_at = NOW()
      WHERE id = ${opts.id} AND recipient_collaborator_id = ${collaboratorId}
    `;
  }
}
