'use client';

/**
 * AI Tools tab — Phase 3 of
 * `_plans/2026-05-19-editor-real-nle-look.md`.
 *
 * Hosts the global AI affordances that used to clutter the top
 * toolbar: drift report, doc-level text overlays, regen captions,
 * regen VO, regen doc. Each tool is a button with an icon,
 * label, and short subtitle so the user knows what they do
 * before clicking.
 *
 * Stateless — every action and disabled-state flag comes from
 * props.
 */

import {
  Activity,
  FileText,
  Film,
  ImageIcon,
  Layers,
  Loader2,
  Mic,
  Sparkles,
  Subtitles as SubtitlesIcon,
  type LucideIcon,
} from 'lucide-react';

interface AIToolsTabProps {
  onDriftReport: () => void;
  onOverlays: () => void;
  overlayCount: number;
  onRegenCaptions: () => void;
  regenCaptionsDisabled: boolean;
  regenCaptionsLabel: string;
  onRegenVO: () => void;
  onRegenDoc: () => void;
  // ─── Batch B: section thumbnail ─────────────────────────────────
  onOpenSectionThumbnail: () => void;
  sectionThumbnailRegionCount: number;
  hasSectionThumbnail: boolean;
  // ─── Batch D: animate-all + brand kit ──────────────────────────
  /** Number of rows that would have a clip generated by Animate All
   *  (already-ready / locked / unprompted rows are excluded). When
   *  zero, the button is disabled with a "nothing to animate" hint. */
  animateAllCandidateCount: number;
  /** Estimated USD cost of the batch at the current default model.
   *  Surfaced inline so the user sees what they're about to spend. */
  animateAllCostUsd: number;
  /** Progress while the batch runs — null when idle. */
  animateAllProgress: { done: number; total: number } | null;
  /** Workspace default broll model id for the inline caption. */
  brollModelId: string;
  onAnimateAll: () => void;
  /** Brand kit channel name to display in the row.
   *  Null when no channel is pinned — the row reads "Default kit". */
  brandKitChannelName: string | null;
  hasBrandKitOverride: boolean;
  /** Open the BrandKitModal. Now clickable instead of read-only. */
  onOpenBrandKit: () => void;
}

export function AIToolsTab({
  onDriftReport,
  onOverlays,
  overlayCount,
  onRegenCaptions,
  regenCaptionsDisabled,
  regenCaptionsLabel,
  onRegenVO,
  onRegenDoc,
  onOpenSectionThumbnail,
  sectionThumbnailRegionCount,
  hasSectionThumbnail,
  animateAllCandidateCount,
  animateAllCostUsd,
  animateAllProgress,
  brollModelId,
  onAnimateAll,
  brandKitChannelName,
  hasBrandKitOverride,
  onOpenBrandKit,
}: AIToolsTabProps): React.ReactElement {
  const animateAllSubtitle = animateAllProgress
    ? `Generating ${animateAllProgress.done}/${animateAllProgress.total}…`
    : animateAllCandidateCount === 0
      ? 'Every shot is already animated or locked'
      : `${animateAllCandidateCount} shot${animateAllCandidateCount === 1 ? '' : 's'} need clips · ~$${animateAllCostUsd.toFixed(2)} via ${brollModelId}`;
  const animateAllDisabled = animateAllProgress !== null || animateAllCandidateCount === 0;

  return (
    <div className="flex flex-col gap-1.5">
      <ToolRow
        icon={animateAllProgress ? Loader2 : Film}
        iconSpinning={Boolean(animateAllProgress)}
        label="Animate all shots"
        subtitle={animateAllSubtitle}
        onClick={onAnimateAll}
        disabled={animateAllDisabled}
        accent="primary"
      />
      <ToolRow
        icon={Activity}
        label="Drift report"
        subtitle="Narration vs shot durations"
        onClick={onDriftReport}
      />
      <ToolRow
        icon={ImageIcon}
        label="Section thumbnail"
        subtitle={
          !hasSectionThumbnail
            ? 'Upload a composite thumbnail for section transitions'
            : sectionThumbnailRegionCount === 0
              ? 'Uploaded — draw regions to enable per-shot zoom'
              : `${sectionThumbnailRegionCount} region${sectionThumbnailRegionCount === 1 ? '' : 's'} drawn`
        }
        onClick={onOpenSectionThumbnail}
      />
      <ToolRow
        icon={Layers}
        label="Text overlays"
        subtitle={
          overlayCount > 0
            ? `${overlayCount} overlay${overlayCount === 1 ? '' : 's'} on the doc`
            : 'Add a doc-level text overlay'
        }
        onClick={onOverlays}
      />
      <ToolRow
        icon={SubtitlesIcon}
        label={regenCaptionsLabel}
        subtitle="Transcribe via gpt-4o-mini-transcribe"
        onClick={onRegenCaptions}
        disabled={regenCaptionsDisabled}
      />
      <ToolRow
        icon={Mic}
        label="Regenerate voiceover"
        subtitle="ElevenLabs from the current scripts"
        onClick={onRegenVO}
      />
      <ToolRow
        icon={FileText}
        label="Regenerate from script"
        subtitle="Edit the script, rebuild the doc"
        onClick={onRegenDoc}
      />

      {/* Brand kit — clickable. Opens the BrandKitModal so the user
          can edit per-doc fonts / colors / logo / channel name
          without leaving the editor. The channel kit itself
          (defaults) still lives on the channel settings page; this
          surface is for the per-doc override. */}
      <ToolRow
        icon={Sparkles}
        label="Brand kit"
        subtitle={
          brandKitChannelName
            ? `Channel: ${brandKitChannelName}${
                hasBrandKitOverride ? ' · with per-doc overrides' : ''
              }`
            : hasBrandKitOverride
              ? 'Per-doc override active (no channel pinned)'
              : 'Default kit'
        }
        onClick={onOpenBrandKit}
        accent={hasBrandKitOverride ? 'primary' : undefined}
      />
    </div>
  );
}

function ToolRow({
  icon: Icon,
  label,
  subtitle,
  onClick,
  disabled,
  iconSpinning,
  accent,
}: {
  icon: LucideIcon;
  label: string;
  subtitle: string;
  onClick: () => void;
  disabled?: boolean;
  iconSpinning?: boolean;
  accent?: 'primary';
}): React.ReactElement {
  const isPrimary = accent === 'primary' && !disabled;
  return (
    <button
      type="button"
      onClick={onClick}
      disabled={disabled}
      className="text-left rounded-md transition-colors flex items-start gap-2.5 p-2"
      style={{
        background: isPrimary ? 'var(--editor-accent-soft)' : 'var(--editor-panel)',
        border: '1px solid',
        borderColor: isPrimary ? 'var(--editor-accent)' : 'var(--editor-edge)',
        opacity: disabled ? 0.5 : 1,
        cursor: disabled ? 'not-allowed' : 'pointer',
      }}
    >
      <div
        className="shrink-0 mt-0.5"
        style={{ color: disabled ? 'var(--fg-muted)' : 'var(--editor-accent)' }}
      >
        <Icon size={14} strokeWidth={2} className={iconSpinning ? 'animate-spin' : ''} />
      </div>
      <div className="min-w-0 flex-1">
        <div className="text-[11px] font-medium" style={{ color: 'var(--fg)' }}>
          {label}
        </div>
        <div className="text-[10px]" style={{ color: 'var(--fg-muted)' }}>
          {subtitle}
        </div>
      </div>
      <Sparkles
        size={11}
        strokeWidth={2}
        style={{ color: 'var(--fg-muted)', opacity: 0.4, flexShrink: 0, marginTop: 4 }}
      />
    </button>
  );
}
