/**
 * Phase 9.6 — permalink page for the weekly digest.
 *
 * Server component (RSC) — reads `insight_digests` directly from the
 * DB so the page is bookmarkable, Slack-able, and email-permalink-able
 * without a client-side fetch round-trip. The session is enforced by
 * the parent (app) layout group; we additionally tenant-scope the
 * read against `session.ws`.
 *
 * URL shape: /insights/2026-05-04 (the Monday that starts the week).
 *
 * Renders the stored body_html (sanitised at write time by the
 * `markdownToBasicHtml` helper that produced it — only h1/h2/p/ul/li/
 * strong are emitted). When the digest doesn't exist yet, shows a
 * friendly placeholder explaining the cron cadence + opt-in toggle.
 */
import { redirect } from 'next/navigation';
import Link from 'next/link';
import { getDigest, listDigests } from '@/lib/weekly-digest';
import { requireUser } from '@/lib/session';
import { DigestPreferencesPanel } from '@/components/insights/DigestPreferencesPanel';

interface PageProps {
  params: Promise<{ week: string }>;
}

const ISO_DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

export default async function InsightsWeekPage({ params }: PageProps) {
  const { week } = await params;
  if (!ISO_DATE_RE.test(week)) {
    // Malformed slug — bounce to the latest digest if any, else /dashboard.
    redirect('/dashboard');
  }
  const session = await requireUser();
  const [digest, recent] = await Promise.all([
    getDigest(session.ws, week),
    listDigests(session.ws, { limit: 8 }),
  ]);

  return (
    <div style={{ padding: 24, maxWidth: 800, margin: '0 auto' }}>
      <div style={{ marginBottom: 16, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <Link
          href="/dashboard"
          style={{ fontSize: 12, color: 'var(--text-muted)', textDecoration: 'none' }}
        >
          ← Dashboard
        </Link>
        <Link
          href="/insights/catalog"
          style={{ fontSize: 12, color: '#7c3aed', textDecoration: 'none' }}
        >
          Browse all videos →
        </Link>
      </div>

      <h1
        className="gradient-text"
        style={{ fontSize: 28, fontWeight: 700, marginBottom: 4 }}
      >
        Weekly insight digest
      </h1>
      <p style={{ fontSize: 13, color: 'var(--text-secondary)', marginBottom: 24 }}>
        Week of {week} (Monday 00:00 UTC → next Monday 00:00 UTC)
      </p>

      {digest ? (
        <article
          className="glass rounded-xl p-6"
          style={{ background: 'rgba(255,255,255,0.02)' }}
        >
          {/*
            body_html is server-generated by markdownToBasicHtml from
            the model's Markdown output. The renderer only emits
            h1/h2/p/ul/li/strong with inline styles — no <script>,
            no <iframe>, no user-supplied attributes — so dangerouslySet
            is acceptable here. The model output flows through the
            sanitising helper, never raw to React.
          */}
          <div
            dangerouslySetInnerHTML={{ __html: digest.body_html }}
            style={{ fontSize: 14, lineHeight: 1.6, color: 'var(--text-primary)' }}
          />
          <div
            style={{
              marginTop: 24,
              paddingTop: 16,
              borderTop: '1px solid rgba(255,255,255,0.08)',
              fontSize: 11,
              color: 'var(--text-muted)',
              display: 'flex',
              gap: 16,
              flexWrap: 'wrap',
            }}
          >
            <span>Generated {new Date(digest.generated_at).toLocaleString()}</span>
            <span>· Model: {digest.ai_model}</span>
            <span>
              · Inputs:{' '}
              {(digest.inputs_summary as { views_recent?: number })?.views_recent?.toLocaleString() ?? '—'}{' '}
              views,{' '}
              {(digest.inputs_summary as { breakouts_count?: number })?.breakouts_count ?? 0} breakouts
            </span>
          </div>
        </article>
      ) : (
        <div
          className="glass rounded-xl p-6"
          style={{
            background: 'rgba(255,255,255,0.02)',
            border: '1px dashed rgba(255,255,255,0.12)',
          }}
        >
          <div style={{ fontSize: 16, fontWeight: 600, marginBottom: 8 }}>
            No digest for this week yet
          </div>
          <p style={{ fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.5 }}>
            The weekly digest cron runs Mondays at 09:00 UTC and only generates a
            digest when the workspace's <code>weekly_digest_enabled</code> flag is
            set AND there's measurable activity in the prior week. Enable it on{' '}
            <Link href="/settings" style={{ color: '#7c3aed', textDecoration: 'underline' }}>
              /settings
            </Link>{' '}
            to start receiving them.
          </p>
        </div>
      )}

      <DigestPreferencesPanel />

      {recent.length > 0 && (
        <section style={{ marginTop: 32 }}>
          <h2
            style={{
              fontSize: 13,
              fontWeight: 600,
              color: 'var(--text-secondary)',
              textTransform: 'uppercase',
              letterSpacing: 0.6,
              marginBottom: 8,
            }}
          >
            Recent weeks
          </h2>
          <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 4 }}>
            {recent.map((r) => (
              <li key={r.week_start}>
                <Link
                  href={`/insights/${r.week_start}`}
                  style={{
                    display: 'flex',
                    justifyContent: 'space-between',
                    padding: '6px 8px',
                    borderRadius: 6,
                    fontSize: 13,
                    color: r.week_start === week ? 'var(--text-primary)' : 'var(--text-secondary)',
                    background: r.week_start === week ? 'rgba(124,58,237,0.08)' : 'transparent',
                    textDecoration: 'none',
                  }}
                >
                  <span>Week of {r.week_start}</span>
                  <span style={{ fontSize: 10, color: 'var(--text-muted)' }}>
                    {new Date(r.generated_at).toLocaleDateString()}
                  </span>
                </Link>
              </li>
            ))}
          </ul>
        </section>
      )}
    </div>
  );
}
