/**
 * Niche Brief — prompt construction + response parsing.
 *
 * The brief is a structured Markdown-free JSON object generated by
 * Perplexity Sonar Deep Research (default) or any other model the
 * operator's picker resolves to. It answers ONE question better than
 * the niche-finder tabs already do: "given THIS operator's channel +
 * production history, can WE win this niche?"
 *
 * Per the council's First-Principles reframe, demand / competition /
 * monetization signals already exist in the 5 tabs that produced the
 * favorite. The brief re-derives them lightly (so the export is
 * self-contained for collaborators) but the load-bearing sections are
 * `operator_fit`, `recommended_angle`, `risks`, and `next_steps`.
 *
 * Per the council's Contrarian critique, every section carries a
 * confidence label ('low' | 'medium' | 'high') so the operator can
 * see when the model is over-claiming. Citations come back tagged by
 * domain quality (handled in perplexity-deep-research.ts) so the UI
 * can flag SEO-blogspam-heavy briefs.
 */
import type { NicheScores } from './types';
import {
  callPerplexityDeepResearch,
  extractFirstJsonBlock,
  type BriefCitation,
  type PerplexityUsage,
} from '@/lib/ai/perplexity-deep-research';

// ---------------------------------------------------------------------------
// Brief shape.
// ---------------------------------------------------------------------------

export type ConfidenceLabel = 'low' | 'medium' | 'high';
export type PromiseLabel = 'Strong' | 'Solid' | 'Marginal' | 'Weak';

/** One channel the brief cites in the competition section. Rendered
 *  as a clickable link in the UI when `channel_id` or `handle`
 *  validates. Both identifiers are model-supplied, hence validated at
 *  render time against strict regexes — bad values fall back to plain
 *  text rather than producing broken URLs. */
export interface BriefCompetitionChannel {
  /** Channel display name. Always present. */
  name: string;
  /** YouTube channel ID — `UC` prefix + 22 chars. Optional. */
  channel_id?: string;
  /** YouTube handle starting with `@`. Optional. */
  handle?: string;
  /** Subscriber count if the model knows it. Display-only. */
  subs?: number;
  /** One-line note on what the channel is known for. Optional. */
  note?: string;
}

/** The 8 sections that make up a brief, in display order. */
export interface BriefSections {
  /** One-sentence verdict. ~25 words. */
  headline: string;
  /** Why the audience is real, how big, trend direction. ~80 words. */
  market_demand: string;
  /** Top channels in the niche, gaps. ~80 words. */
  competition: string;
  /** Structured channel list the UI renders as clickable links below
   *  the competition prose. Optional — older briefs lack the field. */
  competition_channels?: BriefCompetitionChannel[];
  /** RPM range, ad-friendliness, sponsorship + affiliate angles. ~80 words. */
  monetization: string;
  /** "Can THIS operator win this niche?" Grounded in operator context. ~60 words. */
  operator_fit: string;
  /** Saturation, demonetization, COPPA, copyright, etc. ~80 words. */
  risks: string;
  /** Single creative direction. ~50 words. */
  recommended_angle: string;
  /** 3 concrete things the operator could do this week. */
  next_steps: string[];
}

/** Per-section confidence labels. Same keys as BriefSections (minus
 *  `next_steps` and `headline` which are derived). */
export interface SectionConfidences {
  market_demand: ConfidenceLabel;
  competition: ConfidenceLabel;
  monetization: ConfidenceLabel;
  operator_fit: ConfidenceLabel;
  risks: ConfidenceLabel;
  recommended_angle: ConfidenceLabel;
}

/** Full parsed brief, ready to write to the DB. */
export interface ParsedBrief {
  sections: BriefSections;
  /** 0..100 — derived from the section confidences + headline tone. */
  promise_score: number;
  /** Word label corresponding to the promise score band. */
  promise_label: PromiseLabel;
  section_confidences: SectionConfidences;
  citations: BriefCitation[];
  usage: PerplexityUsage;
  cost_usd: number;
  duration_ms: number;
  model_id: string;
}

/** What the operator looks like to the prompt. Fed in verbatim so the
 *  model's `operator_fit` section is grounded in real data, not
 *  hallucination. */
export interface OperatorContext {
  /** Free-text from the workspace's primary channel — "AI productivity
   *  for solopreneurs", "history documentaries", etc. Null when the
   *  workspace has no connected channel yet. */
  channel_description: string | null;
  /** Channel name when available — used for the model's framing. */
  channel_name: string | null;
  /** Niches the workspace has already produced content in. Read from
   *  `niche_favorites` where `outcome = 'produced'` plus any historical
   *  signal we can mine cheaply. */
  produced_niches: string[];
  /** Free-text interest tags. v1 leaves this empty — when the operator-
   *  profile feature lands later it'll populate. */
  interest_tags: string[];
}

// ---------------------------------------------------------------------------
// Prompt construction.
// ---------------------------------------------------------------------------

const SYSTEM_PROMPT = `You are a YouTube niche strategist writing a tight production-decision brief.

Your reader is an operator running a content business. They have already seen the niche's demand, competition, and monetization signals — they don't need you to re-derive those from listicles. What they need is a grounded judgment on whether THIS operator, with the channel context provided, can win this niche.

Hard rules:
1. RETURN ONLY ONE JSON OBJECT. No preamble, no postamble. Wrap it in a \`\`\`json fence if you must, but the JSON object MUST be the only thing inside.
2. Every section MUST end with a confidence label: "low" if your sources were thin or speculative, "medium" if you have some real signal, "high" if you're citing primary or authoritative sources. Be generous with "low" — over-confidence is the failure mode we're guarding against.
3. The operator_fit section is the load-bearing one. Reference the channel description + produced niches the operator gave you. Generic "this could work for anyone" responses fail the brief.
4. risks must be SPECIFIC to this operator + niche combination. "Audience is fickle" is useless; "the top 3 channels in this niche all rely on archival footage which YouTube's recent copyright sweep flagged" is useful.
5. recommended_angle is ONE direction — the single creative bet that gives this operator the best shot. Not three angles, not a buffet.
6. next_steps are 3 concrete actions the operator could do this week. Each starts with a verb.
7. Cite specific sources where you can. The system will flag SEO-blogspam citations automatically; high-quality citations (YouTube data, news, primary research) earn the brief credibility.`;

interface BriefPromptInputs {
  nicheName: string;
  nicheSlug: string;
  scores: NicheScores;
  /** Top-N proof videos saved under the favorite, used as competition signal. */
  proofVideos: ReadonlyArray<{
    title: string;
    channel_title: string | null;
    subscriber_count: number | null;
    view_count: number | null;
    outlier_score: number | null;
    classification: string | null;
  }>;
  operator: OperatorContext;
}

/** Build the user prompt block. Pure function — exported for tests. */
export function buildBriefUserPrompt(inputs: BriefPromptInputs): string {
  const { nicheName, nicheSlug, scores, proofVideos, operator } = inputs;

  const proofVideoLines = proofVideos.length === 0
    ? '(no proof videos saved under this favorite)'
    : proofVideos
        .slice(0, 8)
        .map((v, i) => {
          const channel = v.channel_title ?? 'unknown channel';
          const subs = v.subscriber_count != null ? `${formatNum(v.subscriber_count)} subs` : 'subs unknown';
          const views = v.view_count != null ? `${formatNum(v.view_count)} views` : 'views unknown';
          const outlier = v.outlier_score != null ? `${v.outlier_score.toFixed(1)}× outlier` : '';
          const cls = v.classification ? ` (${v.classification})` : '';
          return `${i + 1}. "${escapeAngle(v.title)}" — ${channel}, ${subs}, ${views}${outlier ? `, ${outlier}` : ''}${cls}`;
        })
        .join('\n');

  const scoreBlock = isPlaceholder(scores)
    ? '(no v0.5 scores yet — the operator favorited this from a video, so demand/competition/monetization signals are NOT pre-computed for you. Use the proof videos and your own research to characterise them.)'
    : [
        `- Demand: ${scores.demand.label} (numeric ${scores.demand.numeric.toFixed(2)}, confidence ${scores.demand.confidence})`,
        `- Crowdedness: ${scores.supply.label} (numeric ${scores.supply.numeric.toFixed(2)}, confidence ${scores.supply.confidence})`,
        `- Monetization: ${scores.monetization.label} ($${scores.monetization.lowUsdPerMille.toFixed(0)}–$${scores.monetization.highUsdPerMille.toFixed(0)} per 1k views, confidence ${scores.monetization.confidence})`,
        `- Fit (existing signal): ${scores.fit.label} (numeric ${scores.fit.numeric.toFixed(2)}, confidence ${scores.fit.confidence})`,
        `- Combined score: ${scores.combined.toFixed(2)}`,
      ].join('\n');

  const channelLine = operator.channel_description
    ? `${operator.channel_name ? `"${operator.channel_name}" — ` : ''}${operator.channel_description}`
    : '(no connected channel description — write operator_fit conservatively, framing it as "if the operator\'s channel skews towards X, then …")';

  const producedLine =
    operator.produced_niches.length === 0
      ? '(no produced niches recorded yet — treat the operator as a generalist building out their slate)'
      : operator.produced_niches.map((n) => `- ${n}`).join('\n');

  const interestsLine =
    operator.interest_tags.length === 0
      ? '(no explicit interest tags — infer fit from the channel description and produced niches)'
      : operator.interest_tags.map((t) => `- ${t}`).join('\n');

  return [
    `# Niche under evaluation`,
    `Name: ${nicheName}`,
    `Slug: ${nicheSlug}`,
    ``,
    `## Pre-computed signals (from the niche-finder scoring engine)`,
    scoreBlock,
    ``,
    `## Proof videos the operator saved under this favorite`,
    proofVideoLines,
    ``,
    `## Operator context`,
    `Channel: ${channelLine}`,
    ``,
    `Niches already produced:`,
    producedLine,
    ``,
    `Interest tags:`,
    interestsLine,
    ``,
    `## Output JSON schema`,
    `Return EXACTLY this JSON shape (no markdown, no prose outside the JSON):`,
    '',
    '```json',
    `{
  "headline": "one-sentence verdict, max 25 words",
  "market_demand": "~80 words on why the audience is real, how big, trend direction. Cite a source if you have one. Confidence: low | medium | high.",
  "competition": "~80 words. Name 2-3 top channels by handle, note their size, identify gaps. Reference the proof videos when relevant. Confidence: low | medium | high.",
  "competition_channels": [
    {
      "name": "Display name of a channel cited in the competition prose",
      "handle": "@channel-handle if you know it (must start with @, alphanumerics/dots/dashes/underscores after)",
      "channel_id": "UCxxxxxxxxxxxxxxxxxxxx if you know it (22 chars after UC)",
      "subs": 123456,
      "note": "one short clause on what this channel does"
    }
  ],
  "monetization": "~80 words on RPM range, ad-friendliness, sponsorship and affiliate angles. Confidence: low | medium | high.",
  "operator_fit": "~60 words. Reference the channel description and produced niches by name. Concrete fit reasoning, not generic. Confidence: low | medium | high.",
  "risks": "~80 words. Specific to THIS operator + THIS niche. COPPA, demonetization, copyright, format risks, audience age, platform dependence. Confidence: low | medium | high.",
  "recommended_angle": "~50 words on the ONE creative direction this operator should bet on. Confidence: low | medium | high.",
  "next_steps": [
    "First concrete action, starting with a verb",
    "Second concrete action",
    "Third concrete action"
  ],
  "section_confidences": {
    "market_demand": "low | medium | high",
    "competition": "low | medium | high",
    "monetization": "low | medium | high",
    "operator_fit": "low | medium | high",
    "risks": "low | medium | high",
    "recommended_angle": "low | medium | high"
  },
  "promise_score": 0
}`,
    '```',
    '',
    `**promise_score** is an integer 0–100. Use this rubric:`,
    `- 80–100: strong, all four pre-computed dimensions (demand/competition/monetization/fit) are favorable AND operator fit is clear`,
    `- 60–79: solid, most dimensions favorable, fit plausible`,
    `- 40–59: marginal, mixed signals, fit unclear`,
    `- 0–39: weak, the operator should probably pass`,
    ``,
    `**competition_channels** must include EVERY channel you name in the competition prose, in the same order. For each, set \`handle\` (preferred, e.g. "@MrBeast") or \`channel_id\` (e.g. "UCX6OQ3DkcsbYNE6H8uQQuVA") so the operator can click straight to that channel on YouTube. Omit identifiers you are not sure about — the UI falls back to plain text rather than show a broken link. Return an empty array if you cite no channels.`,
    ``,
    `If you have no real research backing a section, set its confidence to "low" and say so in the section text. Do NOT invent data to look authoritative.`,
  ].join('\n');
}

function isPlaceholder(s: NicheScores): boolean {
  return s.combined === 0 && s.demand.label === 'low' && s.supply.label === 'saturated';
}

function formatNum(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return String(n);
}

function escapeAngle(s: string): string {
  return s.replace(/[<>]/g, '');
}

// ---------------------------------------------------------------------------
// Response parsing — extract + validate.
// ---------------------------------------------------------------------------

const VALID_CONFIDENCES: readonly ConfidenceLabel[] = ['low', 'medium', 'high'];

function clampConfidence(v: unknown): ConfidenceLabel {
  return typeof v === 'string' && (VALID_CONFIDENCES as readonly string[]).includes(v)
    ? (v as ConfidenceLabel)
    : 'low'; // default to 'low' on invalid — protects against over-claiming
}

function clampString(v: unknown, maxLen = 2000): string {
  if (typeof v !== 'string') return '';
  return v.length > maxLen ? v.slice(0, maxLen) : v;
}

function clampStringArray(v: unknown, maxItems = 5, maxLen = 500): string[] {
  if (!Array.isArray(v)) return [];
  return v
    .filter((s): s is string => typeof s === 'string' && s.length > 0)
    .map((s) => (s.length > maxLen ? s.slice(0, maxLen) : s))
    .slice(0, maxItems);
}

function clampPromiseScore(v: unknown): number {
  const n = typeof v === 'number' ? v : Number(v);
  if (!Number.isFinite(n)) return 0;
  return Math.max(0, Math.min(100, Math.round(n)));
}

/** YouTube channel ID — fixed `UC` prefix + 22 chars of base64url
 *  alphabet. Strict because we feed the value directly into a URL. */
const CHANNEL_ID_RE = /^UC[A-Za-z0-9_-]{22}$/;
/** YouTube handle: leading `@`, then 3-30 chars of alphanumerics
 *  + `._-`. YouTube's own rules are slightly looser (allows some
 *  CJK) but this conservative cut blocks the prompt-injection
 *  shape (no slashes, no URL fragments). */
const CHANNEL_HANDLE_RE = /^@[A-Za-z0-9._-]{3,30}$/;

/** Decode the model's `competition_channels` array. Bad rows are
 *  dropped; bad identifiers within a good row are stripped (the row
 *  still renders as plain text). Caps at 5 entries to keep the brief
 *  body tight. */
function clampCompetitionChannels(v: unknown): BriefCompetitionChannel[] {
  if (!Array.isArray(v)) return [];
  const out: BriefCompetitionChannel[] = [];
  for (const raw of v) {
    if (out.length >= 5) break;
    if (!raw || typeof raw !== 'object') continue;
    const r = raw as Record<string, unknown>;
    const name = typeof r.name === 'string' ? r.name.trim() : '';
    if (name.length === 0 || name.length > 120) continue;
    const channel_id =
      typeof r.channel_id === 'string' && CHANNEL_ID_RE.test(r.channel_id)
        ? r.channel_id
        : undefined;
    const handle =
      typeof r.handle === 'string' && CHANNEL_HANDLE_RE.test(r.handle)
        ? r.handle
        : undefined;
    const subsRaw = typeof r.subs === 'number' ? r.subs : Number(r.subs);
    const subs = Number.isFinite(subsRaw) && subsRaw >= 0 ? Math.round(subsRaw) : undefined;
    const note = typeof r.note === 'string' && r.note.length > 0
      ? (r.note.length > 200 ? r.note.slice(0, 200) : r.note)
      : undefined;
    out.push({ name, channel_id, handle, subs, note });
  }
  return out;
}

function promiseLabelFor(score: number): PromiseLabel {
  if (score >= 80) return 'Strong';
  if (score >= 60) return 'Solid';
  if (score >= 40) return 'Marginal';
  return 'Weak';
}

/** Parse the model's raw response into a validated ParsedBrief.
 *  Throws if the response can't be decoded — the caller writes a
 *  'failed' brief row with the error message. */
export function parseBriefResponse(args: {
  rawContent: string;
  citations: BriefCitation[];
  usage: PerplexityUsage;
  costUsd: number;
  durationMs: number;
  modelId: string;
}): ParsedBrief {
  const parsed = extractFirstJsonBlock<Record<string, unknown>>(args.rawContent);
  if (!parsed) {
    throw new Error(
      `Brief response did not contain a parseable JSON object. First 200 chars: ${args.rawContent.slice(0, 200)}`,
    );
  }

  const sections: BriefSections = {
    headline: clampString(parsed.headline, 500),
    market_demand: clampString(parsed.market_demand, 1500),
    competition: clampString(parsed.competition, 1500),
    competition_channels: clampCompetitionChannels(parsed.competition_channels),
    monetization: clampString(parsed.monetization, 1500),
    operator_fit: clampString(parsed.operator_fit, 1500),
    risks: clampString(parsed.risks, 1500),
    recommended_angle: clampString(parsed.recommended_angle, 1500),
    next_steps: clampStringArray(parsed.next_steps, 5, 500),
  };

  const rawConfidences = (parsed.section_confidences ?? {}) as Record<string, unknown>;
  const section_confidences: SectionConfidences = {
    market_demand: clampConfidence(rawConfidences.market_demand),
    competition: clampConfidence(rawConfidences.competition),
    monetization: clampConfidence(rawConfidences.monetization),
    operator_fit: clampConfidence(rawConfidences.operator_fit),
    risks: clampConfidence(rawConfidences.risks),
    recommended_angle: clampConfidence(rawConfidences.recommended_angle),
  };

  // If the section text is empty, force confidence to 'low' — a section
  // with no content can't be high-confidence.
  for (const key of Object.keys(section_confidences) as (keyof SectionConfidences)[]) {
    if (sections[key as keyof BriefSections] === '') {
      section_confidences[key] = 'low';
    }
  }

  // Minimum viable brief: at least the headline + 2 of the substantive
  // sections must be non-empty. Otherwise the parse "succeeded" but the
  // brief is useless.
  const substantive = [
    sections.market_demand,
    sections.competition,
    sections.monetization,
    sections.operator_fit,
    sections.risks,
    sections.recommended_angle,
  ].filter((s) => s.length > 20);
  if (sections.headline === '' || substantive.length < 2) {
    throw new Error(
      `Brief response was parseable JSON but lacked substance (headline=${sections.headline.length} chars, ${substantive.length} substantive sections).`,
    );
  }

  const promise_score = clampPromiseScore(parsed.promise_score);
  const promise_label = promiseLabelFor(promise_score);

  return {
    sections,
    promise_score,
    promise_label,
    section_confidences,
    citations: args.citations,
    usage: args.usage,
    cost_usd: args.costUsd,
    duration_ms: args.durationMs,
    model_id: args.modelId,
  };
}

// ---------------------------------------------------------------------------
// End-to-end driver — the route handler / cron call this.
// ---------------------------------------------------------------------------

/** Run the full brief pipeline: build prompt → call Perplexity → parse
 *  → return a ParsedBrief ready to persist. Throws on any failure;
 *  caller decides whether to write a failed row + retry. */
export async function generateBrief(args: {
  workspaceId: string;
  modelId: string;
  inputs: BriefPromptInputs;
}): Promise<ParsedBrief> {
  const userPrompt = buildBriefUserPrompt(args.inputs);
  const result = await callPerplexityDeepResearch({
    modelId: args.modelId,
    systemPrompt: SYSTEM_PROMPT,
    userPrompt,
    maxTokens: 4000,
    spend: {
      workspaceId: args.workspaceId,
      featureArea: 'niche_favorite_brief',
      metadata: { niche_slug: args.inputs.nicheSlug },
    },
  });
  return parseBriefResponse({
    rawContent: result.content,
    citations: result.citations,
    usage: result.usage,
    costUsd: result.costUsd,
    durationMs: result.durationMs,
    modelId: args.modelId,
  });
}

// Exported for tests.
export const _internals = {
  isPlaceholder,
  clampConfidence,
  promiseLabelFor,
  SYSTEM_PROMPT,
};
