import type { Migration } from './types';

/**
 * Post-publish "fix the dip" analyses for already-published videos.
 *
 * The companion to migration 0026's pre-publish predictor: this one looks
 * at the REAL retention_curve from `video_analytics` (the audience
 * actually voted with their swipe) and aligns each significant drop in
 * the curve to the script section that was on screen at that moment.
 * The model then proposes a concrete fix per dip.
 *
 * Inputs at analysis time:
 *   - youtube_video_id (must exist in video_analytics with retention_curve)
 *   - script_text (user pastes — we don't have scripts of past videos
 *     in our DB unless they were generated by this app)
 *
 * `retention_curve_snapshot` is a frozen copy of the curve at analysis
 * time, so re-syncing analytics later doesn't make the historical
 * analysis confusing.
 *
 * `source_script_id` ON DELETE SET NULL — analyses outlive the script
 * they were keyed to.
 */
const migration: Migration = {
  id: '0027_create_dip_analyses',
  description: 'Post-publish fix-the-dip analyses (real retention curve → script-aligned per-dip fixes)',

  async up(client) {
    await client.query(`
      CREATE TABLE IF NOT EXISTS dip_analyses (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
        channel_db_id UUID REFERENCES channels(id) ON DELETE SET NULL,
        project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
        source_script_id UUID REFERENCES scripts(id) ON DELETE SET NULL,

        youtube_video_id TEXT NOT NULL,
        video_title TEXT,
        video_duration_seconds INTEGER,

        script_text TEXT NOT NULL,
        retention_curve_snapshot JSONB NOT NULL DEFAULT '[]'::jsonb,
        average_view_percentage NUMERIC(6,3),

        detected_dips JSONB NOT NULL DEFAULT '[]'::jsonb,
        top_fixes JSONB NOT NULL DEFAULT '[]'::jsonb,
        patterns JSONB NOT NULL DEFAULT '[]'::jsonb,

        ai_model TEXT NOT NULL,
        generation_params JSONB NOT NULL DEFAULT '{}'::jsonb,
        notes TEXT,

        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    await client.query(`
      CREATE INDEX IF NOT EXISTS idx_dip_analyses_workspace
        ON dip_analyses(workspace_id, created_at DESC)
    `);
    await client.query(`
      CREATE INDEX IF NOT EXISTS idx_dip_analyses_video
        ON dip_analyses(workspace_id, youtube_video_id)
    `);
    await client.query(`
      CREATE INDEX IF NOT EXISTS idx_dip_analyses_channel
        ON dip_analyses(channel_db_id) WHERE channel_db_id IS NOT NULL
    `);
  },

  async down(client) {
    await client.query(`DROP TABLE IF EXISTS dip_analyses`);
  },
};

export default migration;
