/**
 * Google Cloud Speech-to-Text aligner.
 *
 * Used for voiceovers generated by Google TTS — Google does not expose
 * a built-in forced-alignment endpoint, so we re-recognize the audio
 * with word-level time offsets enabled and project the result against
 * the known script.
 *
 * This is technically ASR, not true forced alignment — the recognizer
 * is free to disagree with the supplied script. In practice for clean
 * TTS-generated audio (no background noise, single speaker) word-level
 * timings are accurate; the projection step matches recognized words
 * against the canonical script by position and uses the script's
 * spelling in the returned `AlignedWord.text`, so proper-noun
 * recognition errors don't leak into the editor highlight.
 *
 * Cost: $0.024/min audio (Google STT v1 standard model, verified
 * 2026-05-25). Caching is the caller's responsibility — typically the
 * cache layer in `src/lib/voiceover-alignment-cache.ts`.
 */

import type { protos } from '@google-cloud/speech';
import { logger } from '../../logger';
import { alignCostUsd } from '../cost';
import { assertGoogleCredentialsValid, loadGoogleCredentials } from '../google-env';
import {
  TtsProviderError,
  type Aligner,
  type AlignRequest,
  type AlignResult,
  type AlignedWord,
} from '../types';

const ALIGNER_ID = 'google-stt' as const;

async function getSpeechClient() {
  const creds = assertGoogleCredentialsValid();
  const { SpeechClient } = await import('@google-cloud/speech');
  return new SpeechClient({
    projectId: creds.projectId,
    credentials: {
      client_email: creds.clientEmail,
      private_key: creds.privateKey,
    },
  });
}

/**
 * Google STT supports a wide language set, but a handful of locales
 * are listed as restricted/preview. We don't gate aggressively — let
 * Google return its own INVALID_ARGUMENT if the locale isn't supported
 * and surface it as a clean error. This avoids a parallel list that
 * could drift out of sync with Google's release notes.
 */
class GoogleSttAligner implements Aligner {
  readonly id = ALIGNER_ID;

  isConfigured(): boolean {
    return loadGoogleCredentials() !== null;
  }

  supportsLanguage(): boolean {
    return true;
  }

  async align(req: AlignRequest): Promise<AlignResult> {
    if (req.audio.byteLength === 0) {
      throw new TtsProviderError(
        'Google STT aligner received empty audio.',
        ALIGNER_ID,
        'invalid_request',
        false,
      );
    }

    logger.info('[tts align google-stt] start', {
      audioBytes: req.audio.byteLength,
      chars: req.text.length,
      languageCode: req.languageCode,
    });

    const client = await getSpeechClient();

    const recognizeRequest: protos.google.cloud.speech.v1.IRecognizeRequest = {
      audio: {
        content: Buffer.from(req.audio).toString('base64'),
      },
      config: {
        // Encoding follows the audio mimeType the caller supplied. We
        // produce WAV (LINEAR16 with header) for Google voices now —
        // STT accepts that via encoding=LINEAR16 + the matching sample
        // rate. ElevenLabs audio comes through as MP3 still.
        ...(req.mimeType === 'audio/wav'
          ? { encoding: 'LINEAR16' as const, sampleRateHertz: 24000 }
          : { encoding: 'MP3' as const }),
        languageCode: req.languageCode,
        enableWordTimeOffsets: true,
        // Picking the latest_long model — better word-time accuracy for
        // narration-length audio than the default. For hyper-short
        // clips (< 5s) `latest_short` would be marginally better but
        // we're optimizing for the YouTube narration use case.
        model: 'latest_long',
      },
    };

    const startedAt = Date.now();
    let response: protos.google.cloud.speech.v1.IRecognizeResponse;
    try {
      const [res] = await client.recognize(recognizeRequest);
      response = res;
    } catch (err) {
      const raw = err instanceof Error ? err.message : String(err);
      const sanitized = raw.replace(/https?:\/\/\S+/g, '<url>').slice(0, 280);
      logger.warn('[tts align google-stt err]', {
        languageCode: req.languageCode,
        detail: sanitized,
      });
      throw classifyGoogleSttError(sanitized);
    }

    const recognizedWords = extractWords(response);
    const projected = projectAgainstScript(recognizedWords, req.text);
    const durationSec =
      projected.length > 0 ? projected[projected.length - 1].endSec : 0;
    const costUsd = alignCostUsd('google-stt', durationSec);

    logger.info('[tts align google-stt] ok', {
      recognizedWordCount: recognizedWords.length,
      projectedWordCount: projected.length,
      durationSec,
      costUsd,
      apiLatencyMs: Date.now() - startedAt,
    });

    return {
      words: projected,
      durationSec,
      costUsd,
      alignerUsed: ALIGNER_ID,
    };
  }
}

function extractWords(
  response: protos.google.cloud.speech.v1.IRecognizeResponse,
): AlignedWord[] {
  const out: AlignedWord[] = [];
  for (const result of response.results ?? []) {
    const top = result.alternatives?.[0];
    if (!top?.words) continue;
    for (const w of top.words) {
      out.push({
        text: w.word ?? '',
        startSec: toSeconds(w.startTime),
        endSec: toSeconds(w.endTime),
      });
    }
  }
  return out;
}

function toSeconds(d?: protos.google.protobuf.IDuration | null): number {
  if (!d) return 0;
  const seconds = Number(d.seconds ?? 0);
  const nanos = Number(d.nanos ?? 0);
  return seconds + nanos / 1e9;
}

/**
 * Walk the recognized-word list in lock-step with the script's word
 * list. The recognizer may merge or split tokens vs. the script, but
 * for clean TTS-output the alignment is usually 1:1 — we trust
 * positional projection and use the script's spelling for the
 * returned `text` so the editor's word-highlight never shows an
 * ASR mistake. If the lengths diverge wildly (>20% mismatch) we
 * return the recognized words as-is so the caller can at least see
 * something is wrong rather than getting silent mis-attribution.
 */
function projectAgainstScript(
  recognized: AlignedWord[],
  script: string,
): AlignedWord[] {
  const scriptWords = script
    .split(/\s+/)
    .map((w) => w.trim())
    .filter(Boolean);

  if (scriptWords.length === 0 || recognized.length === 0) return recognized;

  const lenDelta = Math.abs(scriptWords.length - recognized.length);
  const ratio = lenDelta / Math.max(scriptWords.length, recognized.length);
  if (ratio > 0.2) {
    logger.warn('[tts align google-stt] script projection skipped (length divergence)', {
      scriptWordCount: scriptWords.length,
      recognizedWordCount: recognized.length,
      divergenceRatio: ratio,
    });
    return recognized;
  }

  const projected: AlignedWord[] = [];
  const n = Math.min(scriptWords.length, recognized.length);
  for (let i = 0; i < n; i++) {
    projected.push({
      text: scriptWords[i],
      startSec: recognized[i].startSec,
      endSec: recognized[i].endSec,
    });
  }
  // Any extra script words (the recognizer skipped trailing audio) get
  // appended with the last known end-time so the editor cursor doesn't
  // jump to 0 — better to land on the final word than silently drop it.
  if (scriptWords.length > n) {
    const lastEnd = projected[projected.length - 1]?.endSec ?? 0;
    for (let i = n; i < scriptWords.length; i++) {
      projected.push({ text: scriptWords[i], startSec: lastEnd, endSec: lastEnd });
    }
  }
  return projected;
}

function classifyGoogleSttError(sanitized: string): TtsProviderError {
  const lower = sanitized.toLowerCase();
  if (lower.includes('unauthenticated') || lower.includes('permission_denied')) {
    return new TtsProviderError(
      `Google STT authentication failed: ${sanitized}`,
      ALIGNER_ID,
      'unauthorized',
      false,
      sanitized,
    );
  }
  if (lower.includes('resource_exhausted') || lower.includes('quota')) {
    return new TtsProviderError(
      `Google STT quota exceeded: ${sanitized}`,
      ALIGNER_ID,
      'rate_limited',
      true,
      sanitized,
    );
  }
  if (lower.includes('invalid_argument')) {
    return new TtsProviderError(
      `Google STT rejected the request (likely unsupported language or audio format): ${sanitized}`,
      ALIGNER_ID,
      'invalid_request',
      false,
      sanitized,
    );
  }
  if (lower.includes('deadline') || lower.includes('timeout')) {
    return new TtsProviderError(
      `Google STT timed out: ${sanitized}`,
      ALIGNER_ID,
      'timeout',
      true,
      sanitized,
    );
  }
  return new TtsProviderError(
    `Google STT failed: ${sanitized}`,
    ALIGNER_ID,
    'vendor_5xx',
    true,
    sanitized,
  );
}

export const googleSttAligner: Aligner = new GoogleSttAligner();
